title:  pixel shuffle
email: hello@xiple.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Zita's corner on the www
baseurl: "" # the subpath of your site, e.g. /blog
domain: "https://xiple.co.uk"
url: https://blog.xiple.co.uk # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zita.freeburn
github_username:  dopamine

author:
  name: Zita Freeburn
  url: https://xiple.co.uk
  email: hello@xiple.co.uk

nav_pages:
  -
    title: "Home"
    url: "https://xiple.co.uk"
  - index.md
  - about.md

rss: "atom.xml"


# Build settings
# theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:
 - setup-log.md
 - setup-ideas.md
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - CNAME
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/